spring:
  datasource:
    username: root
    password: abc123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/topay?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
#    微服务配置中心为项目统一配置(满足yyyy-MM-dd HH:mm:ss格式)
#  原本格式yyyy-MM-dd HH:mm:ss不支持
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
##出现404错误 直接抛出NoHandlerFoundException
  mvc:
   throw-exception-if-no-handler-found: true
   # 关闭默认资源映射，会导致static静态资源无法映射
  web:
    resources:
      add-mappings: false
  redis:
    # Redis服务器地址
    host: 127.0.0.1
    # Redis服务器连接端口
    port: 6379
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 100
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 600
        # 连接池中的最小空闲连接
        min-idle: 0
    lettuce:
      shutdown-timeout: 0
      # Redis服务器连接密码
    password: abc123456
mybatis:
  mapper-locations: classpath:/mapper/*.xml
  config-location: classpath:/mybatis-config.xml
logging:
  level:
    com.liust: debug


